### ISSUE TITLE
Add C++20 semaphore

### ISSUE THREAD

**Issue by WilliamTambellini** [AnthonyCalandra/modern-cpp-features#108]
Hi @AnthonyCalandra 
Would you mind if I add an entry for semaphores:
https://en.cppreference.com/w/cpp/thread/counting_semaphore
?

**Comment by AnthonyCalandra** [comment]
Hi William, thanks for your interest in contributing to the sheet. So far I've stayed away from adding most concurrency features just because they probably need detailed explanations (users familiar with writing concurrent code can find better resources than this sheet), there's so many of them to list, and most users likely aren't going to use them so I didn't think it was worth adding them.

However, I have tagged a few feature requests with "good first issue" if you're interested in those (in addition to any other missing features you're aware of).
