### ISSUE TITLE
One of the comment in C++11 for rvalue references is incorrect

### ISSUE THREAD

**Issue by gulipalli123** [AnthonyCalandra/modern-cpp-features#111]
The collection of c++ features is really good. While going through c++11.md, I found one wrong comment.
"int&& xr2 = 0; // `xr2` is an lvalue of type `int&&` -- binds to the rvalue temporary, `0`"

Here xr2 should be rvalue reference as there is no type deduction.

Kindly look into this.

**Comment by AnthonyCalandra** [comment]
Hi @gulipalli123 , this is a common misconception; the comment is actually correct as `xr2` is itself an lvalue, with type `int&&`. See the following post which describes this in detail: http://thbecker.net/articles/rvalue_references/section_05.html

**Comment by gulipalli123** [comment]
Hi Anthony,

From Item24: Distinguish universal references from rvalue references of "Effective Modern C++" , it is clear that it is a rvalue references. Also I have tried compiling with an example, the results are as in the attachment.

![Screenshot from 2022-03-12 08-49-46](https://user-images.githubusercontent.com/46262533/158009325-bb13d169-a5a6-469f-8539-a774782e049e.png)
.

**Comment by gulipalli123** [comment]
Kindly let me know if there is some misunderstanding from myside.

**Comment by AnthonyCalandra** [comment]
Hi @gulipalli123 ,

`xr2` is absolutely an rvalue reference -- there's no doubt about it, I agree. :) However, because the rvalue reference has a name (the name of the variable is `xr2`), it will behave as an lvalue, which is what the comment tries to make clear. There is a distinction between what the value category the reference *binds* to, and what the variable's value category is itself.

To help show you the above explanation in a code example, I have a small one here I want you to try running: https://godbolt.org/z/z8G31q1Gq
Notice there are no universal references here, just an lvalue reference and an rvalue reference.

**Comment by gulipalli123** [comment]
Hi @AnthonyCalandra ,

Thank you for clarifying. My interpretation of your statement was incorrect, I thought you are referring xr2 as lvalue reference but after reading carefully, I understood.
