### ISSUE TITLE
Regarding where C++20's likely, unlikely attribute should appear within a statement

### ISSUE THREAD

**Issue by aesophor** [AnthonyCalandra/modern-cpp-features#97]
README.md says that:

```cpp
int random = get_random_number_between_x_and_y(0, 3);
[[likely]] if (random > 0) {
  // body of if statement
  // ...
}

[[unlikely]] while (unlikely_truthy_condition) {
  // body of while statement
  // ...
}
```

This [Working Draft, Standard for ProgrammingLanguage C++](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/n4885.pdf) (published on 2021-03-17) gives a similar example, but [[unlikely]] appears after the right parenthesis, as opposed to the example given in README.md.

```cpp
if (n > 5) [[unlikely]] {  // n > 5is considered to be arbitrarily unlikely
  g(0);
  return n * 2 + 1;
}
```

Also, [cppreference](https://en.cppreference.com/w/cpp/language/attributes/likely) gives a similar example where [[likely]] appears after the right parenthesis:

```cpp
constexpr double pow(double x, long long n) noexcept {
    if (n > 0) [[likely]]
        return x * pow(x, n - 1);
    else [[unlikely]]
        return 1;
}
```

Regardless of the position of the likely and unlikely attributes, the code will compile. I wonder if there's a difference? If not, should we update the example in README.md?

Thanks!

**Comment by AnthonyCalandra** [comment]
Great question!

Indeed this does compile because attributes are permitted before the if-statement (and others). However, they can also be listed after the condition (to be more precise, at the start of a substatement, ie. the body). So where should these specific attributes go?

I wasn't sure myself so I looked at [the paper](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0479r1.html) where the feature is proposed:

> 7.6.N Likely attribute [dcl.attr.likely]
> 
> The attribute-token likely indicates that a statement has a high probability of being executed. It shall appear at most once in each attribute-list and no attribute-argument-clause shall be present. The likely attribute is not allowed to appear in the same attribute-list as the unlikely attribute.
> 
> **The attribute may be applied to the substatements of selection-statements, to labeled-statements whose label is case or default, or to the substatement of an iteration statement.**

Similar text for the `unlikely` attribute also.

Based on this text and the example given, my README has a bug! Thanks for catching it. I can get around to it once I have some spare time, or you're more than welcome to create a PR if you would like to contribute. This would be a great first issue. :+1:
